zuul:
  routes:
    user:
      path: /api/users/**
      url: http://localhost:8080/users
foo:
  enabled: true
  remote-address: 1.1.1.1
spring:
  application:
    name: spring-workshop
  jpa:
    show-sql: true
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    enabled: false